import { lesson, teacherSources } from './curriculumTypes';
import { exercisePosition } from './exercise';

export const sequenceLessons = [
  lesson('E', 'tactics.capture-direction', '先断接应，再决定追的方向',
    '同样是打吃，方向可能决定对方能否逃走。先找接应的棋，别把对方赶回自己的队伍。',
    '切断白棋与援兵的联系，才能把它赶向狭窄的角。白接长后，再找最后一气。',
    '只让对方少一气还不够；如果这一手帮它接上外面的棋，追击就落空了。', [
      { kind: 'sequence', familyId: 'go.tactics.capture-direction.with-support',
        position: exercisePosition(['.O.OO', '.X.O.', '.....', '.....', '.....']), minimumCaptures: 2,
        prompt: '轮黑。设法吃住上边靠左的白子，并把后续变化下完。',
        hints: ['它的左右都能逃，哪边有白棋接应？', '先切断通往右边援兵的路；白向角里接长后，再填最后一气。'],
        explanation: '先断开接应，白只能向角里接长，仍只剩一气；第二手才真正提子。',
        solution: [{ point: { x: 2, y: 0 }, reply: { x: 0, y: 0 }, text: '白向角接长，但仍只有下面一气。现在轮黑，继续把变化下完。',
          next: [{ point: { x: 0, y: 1 }, text: '白棋已被提走；你完成了打吃、白逃、再提子的完整变化。' }],
          refutations: [{ after: { x: 4, y: 4 }, reply: { x: 0, y: 1 }, text: '黑没有继续填最后一气，白又接长，获得了新的出口。' }] }],
        refutations: [{ after: { x: 0, y: 0 }, reply: { x: 2, y: 0 }, text: '从角里打吃，白向右连上援兵，整块有三气。先看接应在哪边，再决定从哪里追。' }] },
      { kind: 'sequence', familyId: 'go.tactics.capture-direction.with-support',
        position: exercisePosition(['.OO.O', '.XX.O', '.....', '.....', '.....']), minimumCaptures: 3,
        prompt: '轮黑。这次目标是上边靠左的两颗白棋。阻止它们连回，并继续提掉整块。',
        hints: ['白棋两个出口中，哪一个通向自己的队伍？', '先占通往右侧白棋的连接点，再跟着它的应手继续。'],
        explanation: '棋块虽然变大，边界和最后一气的关系没有变；整个变化需要两手黑棋。',
        solution: [{ point: { x: 3, y: 0 }, reply: { x: 0, y: 0 }, text: '白向左角逃，三颗白棋仍只有角下的一气。请继续。',
          next: [{ point: { x: 0, y: 1 }, text: '整块白棋一起被提走。' }] }],
        refutations: [{ after: { x: 0, y: 0 }, reply: { x: 3, y: 0 }, text: '白向右连回，有了两个出口。打吃方向反而帮助它逃出了角。' }] },
    ], ['tactics.escape-atari'], { position: exercisePosition(['.O.OO', '.X.O.', '.....', '.....', '.....']),
      exposedFamilyIds: ['go.tactics.capture-direction.with-support'], steps: [
        { text: '左边白棋的右侧有援兵。黑要先堵住连接点，再追向角里。' },
        { point: { x: 2, y: 0 }, text: '这一手同时切断接应、打吃白子。' },
        { point: { x: 0, y: 0 }, text: '白向角里接长，仍只有下面一气。' },
        { point: { x: 0, y: 1 }, text: '黑填最后一气。决定吃不吃得到的，是第一手有没有先切断援兵。' },
      ] }, [teacherSources.attack], true),
  lesson('F', 'tactics.snapback', '倒扑：被提之后再提回',
    '有时送进去的一颗子被吃，反而让对方整块棋只剩一气；接着可以从原点提回更多棋。',
    '你先投入一子。若对手选择提它，看看连起来的整块棋还剩几气，再找提回的点。',
    '不能把倒扑当作劫：这里回提拿走多颗棋，整张棋盘没有立即恢复原状。', [
      { kind: 'sequence', position: exercisePosition(['.OX..', '.OX..', 'XX...', '.....', '.....']), minimumCaptures: 3,
        prompt: '轮黑，练习倒扑。先投入一子；白提子后，请把变化下完。',
        hints: ['找一手能让对方先提子，却使整块白棋只剩一气的位置。', '先在左上角投一子；白若在下面提子，再数整块白棋的气。'],
        explanation: '先让一颗，再提回三颗。回提改变了整块棋的数量与形状，不是立即还原棋盘。',
        solution: [{ point: { x: 0, y: 0 }, reply: { x: 0, y: 1 }, text: '白提走了角上的黑子；现在三颗白棋只剩刚空出的角点一气。轮黑。',
          next: [{ point: { x: 0, y: 0 }, text: '黑从原点提回整块白棋，这就是倒扑。' }] }] },
      { kind: 'sequence', position: exercisePosition(['.OOX...', '.OOX...', 'XXX....', '.......', '.......', '.......', '.......']), minimumCaptures: 5,
        prompt: '轮黑。白棋块变大了，试着用倒扑把它提掉。白提子后，请把变化下完。',
        hints: ['把白棋看成一整块，比较提子前后它的气。', '先在左上角投入一子；白提子后，看看刚空出的角点。'],
        explanation: '白棋子数变多，倒扑的依据仍是提子以后整块白棋只剩一气。',
        solution: [{ point: { x: 0, y: 0 }, reply: { x: 0, y: 1 }, text: '白把黑子提走了。重新数这整块白棋的气，再下一手。',
          next: [{ point: { x: 0, y: 0 }, text: '从原点回提，这次提走五颗相连的白棋。' }] }] },
    ], ['tactics.ladder'], { position: exercisePosition(['.XO..', '.XO..', 'OO...', '.....', '.....'], 'white'),
      exposedFamilyIds: ['go.tactics.snapback.board-1'], steps: [
        { text: '这次老师执白，演示同一手筋。左上角先投入一颗白棋。' },
        { point: { x: 0, y: 0 }, text: '白投角。这颗白子只有下面一气，对方可以提它。' },
        { point: { x: 0, y: 1 }, text: '黑选择提白。黑的三颗棋连起来后，只剩刚空出的角点一气。' },
        { point: { x: 0, y: 0 }, text: '白立即回提三颗，完成倒扑。先让对方提一子，再抓住它整块棋只剩一气的时机。' },
      ] }, [teacherSources.curriculum], true),
];
