import { lesson, teacherSources } from './curriculumTypes';
import { exercisePosition } from './exercise';

export const foundationLessons = [
  lesson('A', 'rules.place-turn', '落下第一颗棋',
    '棋子放在线的交叉点上。黑白轮流落子，放下的棋子不能挪动。',
    '先找一个空交叉点落子。我会陪你看棋盘怎样变化。',
    '不是放在格子里，也不能覆盖已有棋子。这里先学合法落子，不评选最佳开局。', [
      { kind: 'point', position: exercisePosition(['.....', '.....', '.....', '.....', '.....']),
        rubric: { kind: 'legal' }, prompt: '你执黑。在任意一个空交叉点落下一颗黑棋。',
        hints: ['横线和竖线相交的地方就是落点。', '试试棋盘中央的交叉点；边和角也可以下。'],
        explanation: '第一颗黑棋落好了，接下来轮白。黑白每次各下一颗，落下后不能挪动。' },
      { kind: 'point', position: exercisePosition(['.....', '.X...', '.....', '...O.', '.....']),
        rubric: { kind: 'legal' }, prompt: '还是你执黑。这次盘上已有棋，找一个空交叉点落子。',
        hints: ['已有黑棋或白棋的点都不能覆盖。', '把新棋放在空交叉点上，原来的两颗棋留在原处。'],
        explanation: '已有的棋保持原位，新棋落在空点。这是每一手的第一项检查。' },
    ], [], { position: exercisePosition(['.....', '.....', '.....', '.....', '.....']), steps: [
      { text: '先看棋盘：交叉点可以落子，格子中间不可以。' },
      { point: { x: 2, y: 2 }, text: '黑先下一颗。棋子留在这里，不能像象棋一样移动。' },
      { point: { x: 3, y: 2 }, text: '接下来轮白。白也必须找一个空交叉点。' },
    ] }),
  lesson('A', 'rules.groups-liberties', '数一数，它还能呼吸吗',
    '横竖相连的同色棋是一整块。贴着整块棋的空交叉点叫气，同一个空点只数一次。',
    '沿着棋块的外沿找空点。斜角不算，棋盘外也不算。',
    '数的是不同的空点，不是棋子数，也不是每颗棋子的气简单相加。', [
      { kind: 'number', position: exercisePosition(['.....', '.....', '.XX..', '.....', '.....']),
        rubric: { kind: 'liberties', anchor: { x: 1, y: 2 } }, prompt: '这两颗相连的黑棋一共有几气？数完后填数字。',
        hints: ['两颗黑棋横着连在一起，作为一整块来数。', '上面两点、下面两点、左右各一点；棋子所在的点不算。'],
        explanation: '连成一块后共用全部气。以后判断危险，要看整块棋而不只看一颗。' },
      { kind: 'number', position: exercisePosition(['XX...', 'X....', '.....', '.....', '.....']),
        rubric: { kind: 'liberties', anchor: { x: 0, y: 0 } }, prompt: '角上的三颗黑棋一共有几气？注意有一个空点挨着两颗黑棋。',
        hints: ['沿着这块弯形黑棋找空点；棋盘外没有气。', '右边一点、下面一点、弯角内一点。弯角内不能重复数。'],
        explanation: '同一个空点即使挨着两颗棋，也只是一气；角上的边界不会提供额外的气。' },
    ], ['rules.place-turn'], { position: exercisePosition(['.....', '.....', '.XX..', '.....', '.....'], 'white'), steps: [
      { text: '这两颗黑棋连在一起，共有六个不同的相邻空点。' },
      { point: { x: 1, y: 1 }, text: '白占住上面一个空点，整块黑棋从六气变成五气。' },
    ] }),
  lesson('A', 'rules.capture', '占住最后一气，提走整块',
    '对方整块棋没有气时，会一起被提走。轮到你时，找它剩下的最后一个空点。',
    '先指认目标棋块，再数气，最后才落子。提子后的空点会重新空出来。',
    '一块棋只要还有一气，就还在棋盘上；不能只提走其中一颗。', [
      { kind: 'point', position: exercisePosition(['.X...', 'XOX..', '.....', '.....', '.....']),
        rubric: { kind: 'capture', minimum: 1 }, prompt: '你执黑。白子只剩一气，下一手把它提走。',
        hints: ['白棋的上、左、右都被黑棋挡住了。', '白棋下面唯一的空点，就是最后一气。'],
        explanation: '最后一气被占住，白子离盘；它原来的位置成为空点。' },
      { kind: 'point', position: exercisePosition(['.OOX.', '.XX..', '.....', '.....', '.....']),
        rubric: { kind: 'capture', minimum: 2 }, prompt: '你执黑。上边两颗白棋连成一块，一手把整块提走。',
        hints: ['把两颗白棋当成一个整体；上方是棋盘边界。', '检查这块棋左侧的角点，还有没有别的气？'],
        explanation: '这次只下一颗黑棋，却提掉两颗白棋，因为它们共用同一口气。' },
    ], ['rules.groups-liberties'], { position: exercisePosition(['.OOX.', '.XX..', '.....', '.....', '.....']), steps: [
      { text: '上边两颗白棋连成一块，左上角是它们唯一的气。' },
      { point: { x: 0, y: 0 }, text: '黑占最后一气，两颗白棋一起离盘。' },
    ] }, [teacherSources.capture]),
  lesson('B', 'basics.connect', '把伙伴连成一块',
    '横竖相连才是一块，斜着挨近仍是两块。补上中间的空点，可以把伙伴接起来，共用气。',
    '用眼睛沿着同色棋走一条横竖相连的路。走不过去的地方，就是还没连上。',
    '斜着靠近不等于已经连上；连接也不是把棋子移动到一起。', [
      { kind: 'point', position: exercisePosition(['.....', '.....', '.X.X.', '.....', '.....']),
        rubric: { kind: 'connect', anchors: [{ x: 1, y: 2 }, { x: 3, y: 2 }] }, prompt: '你执黑。下一颗棋，把左右两颗黑棋连成同一块。',
        hints: ['两颗黑棋中间隔着一个空交叉点。', '填上中间的间隔，就能横着连起来。'],
        explanation: '三颗黑棋现在横竖相连，共用整块棋的气。' },
      { kind: 'point', position: exercisePosition(['.....', '.X...', '..X..', '.....', '.....']),
        rubric: { kind: 'connect', anchors: [{ x: 1, y: 1 }, { x: 2, y: 2 }] }, prompt: '两颗黑棋斜着相邻。下一手把它们连成同一块；有不止一个办法。',
        hints: ['找到能同时横竖挨着这两颗黑棋的空点。', '可以从拐角的这一侧连接，也可以从另一侧连接。'],
        explanation: '斜角两侧都能补成横竖相连的路。连接的判断依据是棋块，不是固定坐标。' },
    ], ['rules.capture'], { position: exercisePosition(['.....', '.X...', '..X..', '.....', '.....']), steps: [
      { text: '这两颗黑棋只斜着靠近，还不算一块。' },
      { point: { x: 2, y: 1 }, text: '补上一个拐角，三颗黑棋便连成一块；补另一侧也可以。' },
    ] }, [teacherSources.connection]),
  lesson('B', 'basics.atari', '先看懂打吃的警报',
    '一整块棋只剩一气，叫作被打吃。它还没有被提走，但下一手就可能被吃。',
    '这次先练制造警报：把对方从两气压到一气。真正提子，还需要占住最后一气。',
    '打吃不等于已经吃到；对方也有一回合，可以逃跑、连接或者反提。', [
      { kind: 'point', position: exercisePosition(['.X...', 'XO...', '.....', '.....', '.....']),
        rubric: { kind: 'atari', anchor: { x: 1, y: 1 } }, prompt: '你执黑。让白子只剩一气，给它一次打吃警报。',
        hints: ['白棋还剩右边和下面两气。', '占住其中一气，另一气就成为它最后的出口。'],
        explanation: '白子只剩一气，但还在棋盘上。下一步要看白棋怎样应对，不能把打吃当成提子。' },
      { kind: 'point', position: exercisePosition(['.OO..', '.XX..', '.....', '.....', '.....']),
        rubric: { kind: 'atari', anchor: { x: 1, y: 0 } }, prompt: '这次白棋是一整块两子。下一手让它们共同只剩一气。',
        hints: ['沿上边数整块白棋的气，别把棋盘外算进去。', '白棋左右各有一气。占一边，另一边就成为最后一气。'],
        explanation: '不管棋块有几颗子，共同只剩一气就叫打吃。' },
    ], ['basics.connect'], { position: exercisePosition(['.X...', 'XO...', '.....', '.....', '.....']), steps: [
      { text: '白棋现在有右边和下面两气，我们先占一气。' },
      { point: { x: 2, y: 1 }, text: '白棋只剩下面一气，被打吃了。' },
      { point: { x: 1, y: 2 }, text: '白向下接长，得到了新的气。所以打吃后要重新看棋盘。' },
    ] }, [teacherSources.capture]),
  lesson('B', 'basics.escape', '沿着出口，把棋救出来',
    '自己的棋只剩一气时，先找出口。接长后要重新数整块的气，增加到两气以上才算解除这次打吃。',
    '不是随便在旁边加一颗：新棋必须帮原来的那块棋获得气。',
    '解除一次打吃不代表永远安全；对方落子后还要继续看气。', [
      { kind: 'point', position: exercisePosition(['.O...', 'OXO..', '.....', '.....', '.....']),
        rubric: { kind: 'escape', anchor: { x: 1, y: 1 }, minimumLiberties: 2 }, prompt: '你执黑。中间黑子只剩一气，把它救到至少两气。',
        hints: ['黑棋的上、左、右都没有出口。', '向下面接长，再数新棋块周围的空点。'],
        explanation: '向外接长后，原来的黑子和新棋成为一块，有了更多的气。' },
      { kind: 'point', position: exercisePosition(['XO...', '.....', '.....', '.....', '.....']),
        rubric: { kind: 'escape', anchor: { x: 0, y: 0 }, minimumLiberties: 2 }, prompt: '黑棋在左上角被打吃了。把这颗黑棋救到至少两气。',
        hints: ['棋盘上方和左方没有气，右方被白棋挡住。', '向下面接长，看看右边和下方的新出口。'],
        explanation: '从角上沿边接长，也能获得新的气。先找到原棋块的出口，再看接长后的结果。' },
    ], ['basics.atari'], { position: exercisePosition(['.O...', 'OXO..', '.....', '.....', '.....']), steps: [
      { text: '中央黑子只剩下面一气，下一步必须先照顾它。' },
      { point: { x: 1, y: 2 }, text: '黑接长，原来的棋块从一气变成三气，这次警报解除了。' },
    ] }, [teacherSources.escape]),
];
