-- 1. Create logs table
create table activity_logs (
  id bigint generated by default as identity primary key,
  event_type text not null, -- 'app_start' or 'ai_request'
  user_id uuid references auth.users, -- can be null if anonymous
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Enable RLS
alter table activity_logs enable row level security;

-- 3. Allow anonymous and authenticated inserts
create policy "Allow public insert"
on activity_logs for insert
to anon, authenticated
with check (true);

-- 4. Deny public select (only dashboard admin can see)
create policy "Deny public select"
on activity_logs for select
to anon, authenticated
using (false);

-- Analysis Query (Run this later to get heatmaps)
/*
SELECT 
  EXTRACT(HOUR FROM created_at AT TIME ZONE 'Asia/Shanghai') as hour_of_day,
  COUNT(*) as request_count
FROM activity_logs
WHERE 
  event_type = 'ai_request' 
  AND created_at > (now() - INTERVAL '7 days')
GROUP BY 1
ORDER BY 1 ASC;
*/
