// Declarative architecture contract. ESLint, repository checks and documentation
// consume this data; none should maintain a second dependency matrix or budget.
const extensions = '{ts,tsx,js,jsx,mjs,cjs}';

export const architecture = {
  schemaVersion: 1,
  sourcePolicy: {
    files: [
      '**/*.{ts,tsx}',
      `{agent,core,domains,hooks,components,services,ui,utils,worker}/**/*.${extensions}`,
      `{App,AppController,index}.${extensions}`,
      `harness/**/*.${extensions}`, `tests/**/*.${extensions}`, 'scripts/run-tests.mjs',
    ],
    ignores: ['dist/**', 'node_modules/**', 'android/**', '*.config.js', '*.config.ts'],
    maxEffectiveLines: 400,
    skipBlankLines: true,
    skipComments: true,
    sizeExceptions: [],
    excludedRuntime: [{ path: 'public/service-worker.js', reason: 'Independent browser worker; covered by its dedicated runtime tests.' }],
  },
  qualityPolicy: { noInlineConfig: true, unusedDisableDirectives: 'error', allowedSuppressions: [] },
  // Order is significant: specific compatibility files/facades precede broad folders.
  modules: [
    { id: 'legacy-core', patterns: 'utils/{micro-board,joseki}.ts',
      responsibility: 'Existing board primitives used by core; no permission for arbitrary utils.',
      allow: ['legacy-core', 'shared-types'] },
    { id: 'legacy-bridge', patterns: 'utils/{goLogic,onnx-engine}.ts',
      responsibility: 'Compatibility re-exports; new callers use the corresponding core entry.',
      allow: ['core', 'shared-types'] },
    { id: 'platform-bridge', patterns: 'utils/tapTapBridge.ts',
      responsibility: 'Deprecated TapTap re-exports, with no production callers allowed.', allow: ['platform-sdk'] },
    { id: 'platform-sdk', patterns: 'services/platform/taptap/**',
      responsibility: 'TapTap SDK access, external payload validation and native resource lifetime.',
      allow: ['platform-sdk', 'platform-internal', 'platform-public', 'services', 'shared-types'] },
    { id: 'platform-public', patterns: 'services/platform/{index,environment,haptics,nativeMatchMessages}.ts',
      responsibility: 'Public platform capabilities and wire-message validation used by application code.',
      allow: ['platform-public', 'platform-internal', 'platform-sdk', 'shared-types'] },
    { id: 'platform-internal', patterns: 'services/platform/**',
      responsibility: 'Provider composition and platform implementation contracts, behind public facades.',
      allow: ['platform-internal', 'platform-public', 'platform-sdk', 'shared-types'] },
    { id: 'composition-contract', patterns: 'components/app/AppViewModel.ts',
      responsibility: 'View contract derived from hook types; no hook runtime imports.', allow: [] },
    { id: 'core', patterns: 'core/**', responsibility: 'Pure board, Go/Gomoku rules/search and model inference.',
      allow: ['core', 'legacy-core', 'shared-types'] },
    { id: 'domains', patterns: 'domains/**', responsibility: 'Complete game-position transitions and domain workflows.',
      allow: ['domains', 'core', 'utils', 'shared-types'] },
    { id: 'coach-agent-contract', patterns: 'agent/coach/contract.ts',
      responsibility: 'Shared teaching request/result and Worker message contracts.',
      allow: ['domains', 'services', 'shared-types'] },
    { id: 'coach-agent-client', patterns: 'agent/coach/client.ts',
      responsibility: 'Cancellable teaching Worker bridge with the same-runtime compatibility fallback.',
      allow: ['coach-agent-contract', 'coach-agent-runtime', 'shared-types'] },
    { id: 'coach-agent-runtime', patterns: 'agent/coach/**',
      responsibility: 'UI-independent teaching orchestration; reuse verified rules and provider transport.',
      allow: ['coach-agent-runtime', 'coach-agent-contract', 'coach-provider', 'domains', 'core', 'services', 'shared-types'] },
    { id: 'coach-provider', patterns: 'services/coach/client.ts',
      responsibility: 'Teaching-provider request policy and transport, called only through the agent runtime.',
      allow: ['services', 'shared-types'] },
    { id: 'ui', patterns: 'ui/**', responsibility: 'Reusable presentation primitives without business dependencies.',
      allow: ['ui', 'shared-types'] },
    { id: 'worker', patterns: 'worker/**', responsibility: 'Worker scheduling and engine lifetime; algorithms remain in core.',
      allow: ['worker', 'core', 'legacy-core', 'shared-types'] },
    { id: 'utils', patterns: 'utils/**', responsibility: 'Existing mixed utilities, not the default home for new business logic.',
      allow: ['utils', 'shared-types', 'metadata'] },
    { id: 'components', patterns: 'components/**', responsibility: 'Business UI composed from common UI and public capabilities.',
      allow: ['components', 'composition-contract', 'ui', 'core', 'services', 'platform-public', 'utils', 'shared-types'] },
    { id: 'hooks', patterns: 'hooks/**', responsibility: 'State ownership, user workflows and resource lifecycle.',
      allow: ['hooks', 'coach-agent-client', 'coach-agent-contract', 'domains', 'core', 'services', 'platform-public', 'utils', 'shared-types'] },
    { id: 'services', patterns: 'services/**', responsibility: 'Service adapters; application code uses public platform facades.',
      allow: ['services', 'platform-public', 'platform-internal', 'platform-sdk', 'shared-types'] },
    { id: 'shared-types', patterns: 'types.ts', responsibility: 'Cross-layer domain types, independent of upper layers.', allow: [] },
    { id: 'metadata', patterns: 'package.json', responsibility: 'Repository version and package metadata.', allow: [] },
    { id: 'app', patterns: `{App,AppController,index}.${extensions}`, responsibility: 'Application composition and startup.',
      allow: ['app', 'components', 'composition-contract', 'hooks', 'domains', 'core', 'services', 'platform-public', 'utils', 'shared-types', 'styles'] },
    { id: 'styles', patterns: '*.css', responsibility: 'Application stylesheet assets.', allow: [] },
    { id: 'declarations', patterns: '*.d.ts', responsibility: 'Ambient environment declarations.', allow: [] },
    { id: 'harness', patterns: 'harness/**', responsibility: 'Architecture and verification tooling; no business runtime imports.',
      allow: ['harness', 'metadata'] },
    { id: 'script-adapter', patterns: ['scripts/run-tests.mjs', 'eslint.config.js'],
      responsibility: 'Thin entrypoints into shared harness tooling.', allow: ['harness', 'metadata'] },
    { id: 'tests', patterns: 'tests/**', responsibility: 'Behavioral tests, fixtures and shared test infrastructure.',
      allow: ['*'] },
  ],
  dependencyExceptions: [
    { from: 'composition-contract', to: ['hooks', 'services', 'platform-public', 'utils', 'shared-types'], kind: 'type',
      reason: 'Existing AppViewModel composes hook return types; runtime coupling is forbidden.' },
    { from: 'hooks', fromFiles: ['hooks/gameActions/useEndGameAction.ts', 'hooks/gameActions/useMoveAction.ts'],
      to: ['legacy-bridge'], toFiles: ['utils/goLogic.ts'],
      reason: 'Existing end-game and move actions still import compatibility exports; no new files may do so.' },
  ],
  packageRestrictions: [
    { files: [`agent/**/*.${extensions}`],
      packages: ['react', 'react/**', 'react-dom', 'react-dom/**', '@capacitor/**'],
      message: 'Teaching execution must remain independent of presentation and native SDKs.' },
    { files: [`core/**/*.${extensions}`, 'utils/{micro-board,joseki}.ts'],
      packages: ['react', 'react/**', 'react-dom', 'react-dom/**', '@capacitor/**'],
      message: 'Core rules and inference must stay independent of React and native platform adapters.' },
    { files: [`components/**/*.${extensions}`, `ui/**/*.${extensions}`], packages: ['@capacitor/**'],
      message: 'UI code must use the platform service instead of native SDKs.' },
  ],
  propertyRestrictions: [
    { files: ['**/*.{ts,tsx,js,jsx,mjs,cjs}'], ignores: ['services/platform/taptap/**', 'tests/**'], property: 'tap',
      message: 'Access the TapTap SDK only inside services/platform/taptap; use the public platform service here.' },
  ],
  reuseEntries: [
    { id: 'teaching-exercise', responsibility: 'Course practice and personal review exercises share Go rules, grading and isolated position application.',
      entryPoints: [{ path: 'domains/coach/exercise.ts', exports: ['gradeExercise', 'applyExerciseGrade'] }],
      verification: 'Course, review exercise and stale-session regressions; independent missing-export counterexample.',
      limits: 'Rule-checkable objectives do not prove best play, advanced life and death or expert content quality.' },
    { id: 'teaching-agent', responsibility: 'UI sends complete positions and intent; the agent owns evidence, prompts, provider calls and local fallback.',
      entryPoints: [{ path: 'agent/coach/client.ts', exports: ['runCoachAgent'] }],
      verification: 'Runtime, Worker cancellation and hook stale-reply regressions; independent ESLint boundary counterexamples.',
      limits: 'This is in-app execution separation, not a hosted backend or a secret-hiding boundary; browser CORS still applies.' },
    { id: 'game-position', responsibility: 'Read/write one complete position, including history and both capture counts.',
      entryPoints: [
        { path: 'domains/game/positionState.ts', exports: ['GamePosition', 'PositionAccess', 'createInitialPosition', 'recordMove', 'recordPass', 'undoPosition'] },
        { path: 'hooks/useGameState.ts', exports: ['useGameState'] },
      ], verification: 'PositionAccess readPosition/writePosition and readonly compatibility refs are checked by TypeScript and transition regressions.',
      limits: 'Static imports do not prove that a caller uses a complete snapshot or prevent a renamed duplicate state machine.' },
    { id: 'go-rules', responsibility: 'Reuse Go legality and scoring; live estimates and final scoring have distinct semantics.',
      entryPoints: [
        { path: 'core/go/rules.ts', exports: ['attemptMove'] },
        { path: 'core/go/scoring.ts', exports: ['calculateScore', 'calculateModelScore'] },
        { path: 'core/go/liveEstimate.ts', exports: ['estimateLiveLead'] },
      ], verification: 'Core dependency boundaries and Go/scoring behavioral regressions.',
      limits: 'Reviewers must identify copied rule or scoring algorithms; the harness does not compare semantics.' },
    { id: 'go-search', responsibility: 'One ownership-search implementation for Go analysis and Hard move selection.',
      entryPoints: [{ path: 'core/inference/search.ts', exports: ['runOwnershipSearch'] }],
      verification: 'Worker and event-loop cancellation regressions exercise the shared search.',
      limits: 'An alternative implementation under a different name is not detected automatically.' },
    { id: 'gomoku-search', responsibility: 'One shared Gomoku search with explicit sync/Worker profiles.',
      entryPoints: [
        { path: 'core/gomoku/search.ts', exports: ['searchGomoku', 'getGomokuCandidates'] },
        { path: 'core/gomoku/profiles.ts', exports: ['getGomokuSearchProfile', 'GomokuSearchProfile'] },
      ], verification: 'Sync/Worker tactics, board restoration and shared-search regressions.',
      limits: 'The dependency graph cannot prove equivalence of rewritten algorithms or budgets.' },
    { id: 'worker-protocol', responsibility: 'Main thread and Worker share request identities and message contracts.',
      entryPoints: [{ path: 'core/inference/protocol.ts', exports: ['RequestIdentity', 'WorkerInMessage', 'WorkerOutMessage', 'WorkerReply'] }],
      verification: 'TypeScript and scheduler/Worker/hook lifecycle regressions.',
      limits: 'TypeScript alone cannot validate unknown runtime payloads or stop a differently named duplicate type.' },
    { id: 'platform', responsibility: 'Application callers use public capabilities; native SDK data is validated in the adapter.',
      entryPoints: [
        { path: 'services/platform/index.ts', exports: ['platform', 'getPlatform'] },
        { path: 'services/platform/environment.ts', exports: ['isTapTapEnv'] },
        { path: 'services/platform/haptics.ts', exports: ['tryTapVibration'] },
        { path: 'services/platform/nativeMatchMessages.ts', exports: ['NativeMatchMessage', 'parseNativeMatchMessage'] },
      ], verification: 'ESLint blocks SDK/provider internals and compatibility bridges outside named exceptions; fake SDK tests verify lifecycle.',
      limits: 'Native TapTap behavior still requires device/runtime acceptance.' },
    { id: 'common-ui', responsibility: 'Reuse existing Modal, Button and Toast before inventing equivalent controls.',
      entryPoints: [{ path: 'ui/common/index.ts', exports: ['Modal', 'Button', 'Toast'] }],
      verification: 'Shared UI dependency boundaries and caller render/behavior regressions.',
      limits: 'Similarity of UI or visual design remains a human/browser review responsibility.' },
  ],
  limitations: [
    'Literal static/dynamic imports and require calls are checked; computed module paths are not a sandbox boundary.',
    'Allowed file-level legacy exceptions still require review when imports change within those existing files.',
    'Named reuse entries describe ownership; semantic copies, renamed duplicates and actual UI quality cannot be proven by lint.',
    'JavaScript files receive architecture checks but do not gain TypeScript type safety merely by being linted.',
  ],
};
