import type React from 'react';
import type { MutableRefObject } from 'react';
import type { TsumegoLevel } from '../../utils/tsumegoData';
import type { TsumegoSet } from '../TsumegoListModal';
import type { GameMode, GameType, Player, AchievementDef, DisplayAchievement, UserAchievement } from '../../types';
import type { useAppSettings } from '../../hooks/useAppSettings';
import type { useGameState } from '../../hooks/useGameState';
import type { AppProfile, AppSession } from '../../services/platform';
import type { SGFNode } from '../../utils/sgfParser';
import type { GameSettingsData } from '../SettingsModal';

type AppSettingsReturn = ReturnType<typeof useAppSettings>;
type GameStateReturn = ReturnType<typeof useGameState>;
type OnlineStatus = 'disconnected' | 'connecting' | 'connected';
type StartGameHandler = (mode: 'PvP' | 'PvAI', aiType?: 'local' | 'fun', gameType?: GameType) => void;

export interface AppViewModel {
  achievementsList: AchievementDef[];
  aiTurnLock: MutableRefObject<boolean>;
  cancelMatchmaking: () => void;
  createRoom: () => void;
  clearNewUnlocked: () => void;
  completedLevelIds: string[];
  consecutivePasses: number;
  displayLead: number | null;
  displayTerritory: Float32Array | null;
  displayWinRate: number | null;
  eloDiffStyle: 'gold' | 'normal' | 'negative' | null;
  eloDiffText: string | null;
  exitTsumegoMode: (nextGameMode?: GameMode) => void;
  gameCopied: boolean;
  gameState: GameStateReturn;
  gameTypeRef: MutableRefObject<GameType>;
  handleApplySettings: (newSettings: GameSettingsData) => void;
  handleCopy: () => void;
  handleExportSGF: () => void;
  handleHint: () => void;
  handleImport: () => void;
  handleIntersectionClick: (x: number, y: number) => void;
  handleNextTsumego: () => void;
  handlePass: (isRemote?: boolean) => void;
  handlePrevProblem: () => void;
  handleRetryTsumego: () => void;
  handleSelectTsumegoSet: (set: TsumegoSet) => void;
  handleSignOut: () => void;
  handleStartGame: StartGameHandler;
  handleTapTapLogin: () => void;
  handleUndo: () => void;
  handleUpdateNickname: (nickname: string) => void | Promise<void>;
  hasNextProblem: boolean;
  hasPrevProblem: boolean;
  hideOfflineLoading: boolean;
  importKey: string;
  isFirstRun: boolean;
  isCreatingRoom: boolean;
  isJoiningRoom: boolean;
  isMatching: boolean;
  isWebInitializing: boolean;
  matchBoardSize: number;
  matchTime: number;
  myColor: Player | null;
  newUnlocked: DisplayAchievement | null;
  onlineStatus: OnlineStatus;
  roomId: string | null;
  resetGame: (keepOnline?: boolean, explicitSize?: number, shouldBroadcast?: boolean) => void;
  session: AppSession | null;
  setCurrentTsumegoLevel: (level: TsumegoLevel | null) => void;
  setHideOfflineLoading: (hide: boolean) => void;
  setImportKey: (key: string) => void;
  setIsThinking: (thinking: boolean) => void;
  setShowAboutModal: (show: boolean) => void;
  setShowImportModal: (show: boolean) => void;
  setShowLoginModal: (show: boolean) => void;
  setShowMenu: (show: boolean) => void;
  setShowOnlineMenu: (show: boolean) => void;
  setShowSkinShop: (show: boolean) => void;
  setShowStartScreen: (show: boolean) => void;
  setShowTerritory: React.Dispatch<React.SetStateAction<boolean>>;
  setShowTsumegoLevelSelector: (show: boolean) => void;
  setShowTsumegoList: (show: boolean) => void;
  setShowTsumegoResult: (show: boolean) => void;
  setShowTutorial: (show: boolean) => void;
  setShowUserPage: (show: boolean) => void;
  setToastMsg: (message: string | null) => void;
  setTsumegoCollection: (collection: SGFNode[] | null) => void;
  settings: AppSettingsReturn;
  showAboutModal: boolean;
  showImportModal: boolean;
  showLoginModal: boolean;
  showMenu: boolean;
  showOnlineMenu: boolean;
  showSkinShop: boolean;
  showStartScreen: boolean;
  showTerritory: boolean;
  showThinkingStatus: boolean;
  showTsumegoLevelSelector: boolean;
  showTsumegoList: boolean;
  showTsumegoResult: boolean;
  showTutorial: boolean;
  showUserPage: boolean;
  startMatchmaking: (boardSize: number) => void;
  joinRoom: (roomId: string) => void;
  startTsumego: (root: SGFNode) => void;
  stopWebThinking: () => void;
  toastMsg: string | null;
  tsumegoCollection: SGFNode[] | null;
  tsumegoIsCorrect: boolean;
  tsumegoResultMsg: string;
  tsumegoSetTitle: string;
  userAchievements: Record<string, UserAchievement>;
  userProfile: AppProfile | null;
  vibrate: (pattern: number | number[]) => void;
  webAiEngine: Pick<ReturnType<typeof import('../../hooks/useWebKataGo').useWebKataGo>, 'requestAnalysis'>;
  webInitStatus: string | null;
}
