import type React from 'react';
import type { MutableRefObject } from 'react';
import type { GameType, Player, AchievementDef, DisplayAchievement, UserAchievement, GameSettingsData } from '../../types';
import type { useAppSettings } from '../../hooks/useAppSettings';
import type { useGameState } from '../../hooks/useGameState';
import type { useCoachSession } from '../../hooks/useCoachSession';
import type { useCoachSettings } from '../../hooks/useCoachSettings';
import type { useGameReview } from '../../hooks/useGameReview';
import type { useTeachingWorkspace } from '../../hooks/useTeachingWorkspace';
import type { AppProfile, AppSession } from '../../services/platform';

type AppSettingsReturn = ReturnType<typeof useAppSettings>;
type GameStateReturn = ReturnType<typeof useGameState>;
type OnlineStatus = 'disconnected' | 'connecting' | 'connected';
type StartGameHandler = (mode: 'PvP' | 'PvAI', aiType?: 'local' | 'fun', gameType?: GameType) => void;
export type TutorialContent = ReturnType<typeof useTeachingWorkspace>['tutorialContent'];

export interface AppViewModel {
  coach: ReturnType<typeof useCoachSession>;
  coachSettings: ReturnType<typeof useCoachSettings>;
  review: ReturnType<typeof useGameReview>;
  teaching: ReturnType<typeof useTeachingWorkspace>;
  handleOpenLearning: () => void;
  handleSaveReview: () => void;
  handleInspectReview: (position: ReturnType<GameStateReturn['readPosition']>) => void;
  handleEnterReview: () => void;
  handleStartCoach: () => void;
  handleReturnHome: () => void;
  achievementsList: AchievementDef[];
  aiTurnLock: MutableRefObject<boolean>;
  cancelMatchmaking: () => void;
  createRoom: () => void;
  clearNewUnlocked: () => void;
  consecutivePasses: number;
  displayLead: number | null;
  displayTerritory: Float32Array | null;
  displayWinRate: number | null;
  eloDiffStyle: 'gold' | 'normal' | 'negative' | null;
  eloDiffText: string | null;
  gameCopied: boolean;
  gameState: GameStateReturn;
  viewPosition: ReturnType<GameStateReturn['readPosition']>;
  gameTypeRef: MutableRefObject<GameType>;
  handleApplySettings: (newSettings: GameSettingsData) => void;
  handleCopy: () => void;
  handleExportSGF: () => void;
  handleImport: () => void;
  handleIntersectionClick: (x: number, y: number) => void;
  handlePass: (isRemote?: boolean) => void;
  handleSignOut: () => void;
  handleStartGame: StartGameHandler;
  handleTapTapLogin: () => void;
  handleUndo: () => void;
  handleUpdateNickname: (nickname: string) => void | Promise<void>;
  hideOfflineLoading: boolean;
  importKey: string;
  isFirstRun: boolean;
  isCreatingRoom: boolean;
  isJoiningRoom: boolean;
  isMatching: boolean;
  isWebInitializing: boolean;
  matchBoardSize: number;
  matchTime: number;
  myColor: Player | null;
  newUnlocked: DisplayAchievement | null;
  onlineStatus: OnlineStatus;
  roomId: string | null;
  resetGame: (keepOnline?: boolean, explicitSize?: number, shouldBroadcast?: boolean) => void;
  session: AppSession | null;
  setHideOfflineLoading: (hide: boolean) => void;
  setImportKey: (key: string) => void;
  setIsThinking: (thinking: boolean) => void;
  setShowAboutModal: (show: boolean) => void;
  setShowImportModal: (show: boolean) => void;
  setShowLoginModal: (show: boolean) => void;
  setShowMenu: (show: boolean) => void;
  setShowOnlineMenu: (show: boolean) => void;
  setShowSkinShop: (show: boolean) => void;
  setShowStartScreen: (show: boolean) => void;
  setShowTutorial: (show: boolean) => void;
  setShowTerritory: React.Dispatch<React.SetStateAction<boolean>>;
  setShowUserPage: (show: boolean) => void;
  settings: AppSettingsReturn;
  showAboutModal: boolean;
  showImportModal: boolean;
  showLoginModal: boolean;
  showMenu: boolean;
  showOnlineMenu: boolean;
  showSkinShop: boolean;
  showStartScreen: boolean;
  showTutorial: boolean;
  showTerritory: boolean;
  showThinkingStatus: boolean;
  showUserPage: boolean;
  startMatchmaking: (boardSize: number) => void;
  joinRoom: (roomId: string) => void;
  stopWebThinking: () => void;
  toastMsg: string | null;
  userAchievements: Record<string, UserAchievement>;
  userProfile: AppProfile | null;
  vibrate: (pattern: number | number[]) => void;
  webInitStatus: string | null;
}
